### ISSUE TITLE
Ability to specify context for callback

### ISSUE THREAD

**Issue by vitkarpov** [oleggromov/true-pubsub#1]
It would be convenient to specify context for callback. For instance,

``` js
var pubsub = new require('true-pubsub');
var app = {
  init: function() {
    pubsub.on('foo', this.onFooHandler, this);
  },
  onFooHandler: function() {
    // this refers to app when the pubsub calls the handler
  }
};

app.init();
pubsub.emit('foo');
```

**Comment by oleggromov** [comment]
Why not to bind the callback to the needed context?

``` javascript
pubsub.on('foo', this.onFooHandler.bind(this))
```

This is a much better approach I think because it prevents odd functionality overblow and leaves the control over the callback context on your application code. Do you really need this?

**Comment by vitkarpov** [comment]
Yep. Seems it's just a sugar, so it's unnecessary. Thanks!

**Comment by oleggromov** [comment]
Thank you for feedback and attention, dude!
