### ISSUE TITLE
PubSub works like a charm!

### ISSUE THREAD

**Issue by vitkarpov** [oleggromov/true-pubsub#2]
I have use pubsub in [jblocks](https://github.com/vitkarpov/jblocks/blob/master/lib/index.js#L11) and refused from my own implementation. The code has been reduced and pubsub works like a charm!

Thanks!

**Comment by oleggromov** [comment]
I'm very glad it helps! 👍

**Comment by oleggromov** [comment]
JFYI: you can also transform any object into observable instance like this:

``` javascript

var myObject = new MyObject;
var pubSub = new PubSub;

extend(myObject, pubSub) // you need something like node-extend
```

After this manipulation your instance gets all pubsub methods, i.e. becomes an observable.

**Comment by vitkarpov** [comment]
I thought about it, but couldn't understand how to preserve jsdoc for this methods. I have doc generated from source, if there're no explicit methods then there're no docs for them.

**Comment by vitkarpov** [comment]
Maybe I should just preserve jsdoc stand alone.
